import { useQuery } from '@tanstack/react-query';
import { isSupabaseConfigured, supabase } from '../services/supabase/client';

export type FeedType = 'text' | 'card_showcase' | 'card_added' | 'card_listed' | 'trade_completed';

export interface FeedCard {
  id: string;
  name: string;
  imageUrlSmall: string | null;
}

/** One feed item — an activity event; card_added / card_listed bundle multiple cards. */
export interface FeedItem {
  id: string;
  type: FeedType;
  body: string | null;
  createdAt: string;
  author: { id: string; username: string; displayName: string | null; avatarUrl: string | null };
  cards: FeedCard[];
}

const GROUP_WINDOW_MS = 30 * 60 * 1000; // bundle a burst of adds/listings within 30 min

/**
 * Activity feed: what the user and the people they follow have been doing —
 * adding cards to their collection, listing cards for trade. Auto-generated by
 * DB triggers (0013); no manual posting. A burst of the same activity by one
 * user is grouped into a single item (e.g. "added 12 cards").
 */
export function useFeed(userId: string | undefined) {
  return useQuery({
    queryKey: ['feed', userId],
    enabled: isSupabaseConfigured && Boolean(userId),
    queryFn: async (): Promise<FeedItem[]> => {
      const { data: follows, error: followsError } = await supabase!
        .from('follows')
        .select('followee_id')
        .eq('follower_id', userId!);
      if (followsError) throw followsError;

      const authorIds = [userId!, ...(follows ?? []).map((f: any) => f.followee_id)];

      const { data, error } = await supabase!
        .from('posts')
        .select(
          'id, type, body, created_at, author:profiles(id, username, display_name, avatar_url), card:cards(id, name, image_url_small)'
        )
        .in('author_id', authorIds)
        .order('created_at', { ascending: false })
        .limit(80);
      if (error) throw error;

      const rows = (data ?? []).map((row: any) => ({
        id: row.id as string,
        type: row.type as FeedType,
        body: row.body as string | null,
        createdAt: row.created_at as string,
        author: {
          id: row.author.id,
          username: row.author.username,
          displayName: row.author.display_name,
          avatarUrl: row.author.avatar_url,
        },
        card: row.card
          ? { id: row.card.id, name: row.card.name, imageUrlSmall: row.card.image_url_small }
          : null,
      }));

      // Group consecutive card_added / card_listed by the same author within a window.
      const items: FeedItem[] = [];
      for (const r of rows) {
        const last = items[items.length - 1];
        const groupable = r.type === 'card_added' || r.type === 'card_listed';
        const sameBurst =
          last &&
          groupable &&
          last.type === r.type &&
          last.author.id === r.author.id &&
          new Date(last.createdAt).getTime() - new Date(r.createdAt).getTime() < GROUP_WINDOW_MS;

        if (sameBurst) {
          if (r.card) last!.cards.push(r.card);
        } else {
          items.push({
            id: r.id,
            type: r.type,
            body: r.body,
            createdAt: r.createdAt,
            author: r.author,
            cards: r.card ? [r.card] : [],
          });
        }
      }
      return items;
    },
  });
}
