import { useQuery } from '@tanstack/react-query';
import { isSupabaseConfigured, supabase } from '../services/supabase/client';

export type FeedType = 'text' | 'card_showcase' | 'card_added' | 'card_listed' | 'card_wishlisted' | 'trade_completed';

export interface FeedCard {
  id: string;
  name: string;
  imageUrlSmall: string | null;
}

/** One feed item — an activity event; card_added / card_listed bundle multiple cards. */
export interface FeedItem {
  id: string;
  type: FeedType;
  body: string | null;
  createdAt: string;
  author: { id: string; username: string; displayName: string | null; avatarUrl: string | null };
  authorFollowed: boolean;
  cards: FeedCard[];
}

const GROUP_WINDOW_MS = 30 * 60 * 1000; // bundle a burst of adds/listings within 30 min

/**
 * Activity feed: what people have been doing — adding cards, listing for trade.
 * Auto-generated by DB triggers (0013); no manual posting. Shows posts from
 * *everyone* (so new users with no follows still see a lively feed), but ranks
 * people you follow first, then local collectors (same city), then everyone
 * else by recency. Banned users are hidden. A burst of the same activity by one
 * user is grouped into a single item (e.g. "added 12 cards").
 */
export function useFeed(userId: string | undefined, meLocation?: string | null) {
  return useQuery({
    queryKey: ['feed', userId, meLocation ?? null],
    enabled: isSupabaseConfigured && Boolean(userId),
    queryFn: async (): Promise<FeedItem[]> => {
      const { data: follows, error: followsError } = await supabase!
        .from('follows')
        .select('followee_id')
        .eq('follower_id', userId!);
      if (followsError) throw followsError;
      const followed = new Set<string>((follows ?? []).map((f: any) => f.followee_id));

      const { data, error } = await supabase!
        .from('posts')
        .select(
          'id, type, body, created_at, author:profiles(id, username, display_name, avatar_url, location_name, is_banned), card:cards(id, name, image_url_small)'
        )
        .order('created_at', { ascending: false })
        .limit(150);
      if (error) throw error;

      // Priority: your own + followed (0) → local same-city (1) → everyone else (2).
      const priority = (author: any): number => {
        if (author.id === userId || followed.has(author.id)) return 0;
        if (meLocation && author.location_name && author.location_name === meLocation) return 1;
        return 2;
      };

      const rows = (data ?? [])
        .filter((row: any) => row.author && !row.author.is_banned)
        // If you've set a location, only show non-followed people who share your
        // city (they're the ones you could actually meet up with). With no
        // location set, fall back to showing everyone so the feed isn't empty.
        .filter((row: any) => !meLocation || priority(row.author) < 2)
        .map((row: any) => ({
          id: row.id as string,
          type: row.type as FeedType,
          body: row.body as string | null,
          createdAt: row.created_at as string,
          _priority: priority(row.author),
          author: {
            id: row.author.id,
            username: row.author.username,
            displayName: row.author.display_name,
            avatarUrl: row.author.avatar_url,
          },
          card: row.card
            ? { id: row.card.id, name: row.card.name, imageUrlSmall: row.card.image_url_small }
            : null,
        }))
        // Stable sort: priority bucket first, then most-recent within each bucket
        // (keeps a single author's burst adjacent so grouping still works).
        .sort((a, b) => a._priority - b._priority || new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());

      // Group consecutive card_added / card_listed by the same author within a window.
      const items: FeedItem[] = [];
      for (const r of rows) {
        const last = items[items.length - 1];
        const groupable = r.type === 'card_added' || r.type === 'card_listed' || r.type === 'card_wishlisted';
        const sameBurst =
          last &&
          groupable &&
          last.type === r.type &&
          last.author.id === r.author.id &&
          new Date(last.createdAt).getTime() - new Date(r.createdAt).getTime() < GROUP_WINDOW_MS;

        if (sameBurst) {
          if (r.card) last!.cards.push(r.card);
        } else {
          items.push({
            id: r.id,
            type: r.type,
            body: r.body,
            createdAt: r.createdAt,
            author: r.author,
            authorFollowed: r.author.id === userId || followed.has(r.author.id),
            cards: r.card ? [r.card] : [],
          });
        }
      }
      return items;
    },
  });
}
