import { useMemo } from 'react';
import { ActivityIndicator, FlatList, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { FeedAd } from '../../src/components/FeedAd';
import { PostCard } from '../../src/components/PostCard';
import { SupabaseSetupNotice } from '../../src/components/SupabaseSetupNotice';
import { useAuth } from '../../src/context/AuthContext';
import { useFeed, type FeedItem } from '../../src/hooks/useFeed';
import { useScreenView } from '../../src/services/analytics';
import { isSupabaseConfigured } from '../../src/services/supabase/client';

const AD_EVERY = 5; // one sponsored slot per 5 posts

type FeedRow = { kind: 'post'; item: FeedItem } | { kind: 'ad'; key: string };

/**
 * Home tab = activity feed of what you and the people you follow have been doing:
 * adding cards to their collection and listing cards for trade. Auto-generated by
 * DB triggers (no manual posting); a burst of adds is grouped into one item.
 */
export default function FeedScreen() {
  const { user, profile, loading: authLoading } = useAuth();
  const { data: items, isLoading, isRefetching, refetch } = useFeed(user?.id, profile?.locationName);
  useScreenView('feed');

  // Interleave a sponsored slot every AD_EVERY posts.
  const rows = useMemo<FeedRow[]>(() => {
    const out: FeedRow[] = [];
    (items ?? []).forEach((item, i) => {
      out.push({ kind: 'post', item });
      if ((i + 1) % AD_EVERY === 0) out.push({ kind: 'ad', key: `ad-${item.id}` });
    });
    return out;
  }, [items]);

  if (!isSupabaseConfigured) {
    return (
      <View style={styles.container}>
        <SupabaseSetupNotice />
        <Text style={styles.muted}>Connect Supabase to see your friends' feed.</Text>
      </View>
    );
  }

  if (authLoading) {
    return <ActivityIndicator style={styles.center} />;
  }

  if (!user) {
    return (
      <View style={styles.container}>
        <Text style={styles.emptyTitle}>Welcome to CardLink</Text>
        <Text style={styles.muted}>Sign in to see what the collectors you follow are up to.</Text>
      </View>
    );
  }

  if (isLoading) {
    return <ActivityIndicator style={styles.center} />;
  }

  if (!items?.length) {
    return (
      <FlatList
        data={[]}
        renderItem={null}
        refreshControl={<RefreshControl refreshing={isRefetching} onRefresh={refetch} />}
        contentContainerStyle={styles.emptyWrap}
        ListEmptyComponent={
          <View style={styles.container}>
            <Text style={styles.emptyTitle}>Your feed is quiet</Text>
            <Text style={styles.muted}>
              Follow other collectors and you'll see it here whenever they add cards or list something
              for trade. Add cards to your own collection and your feed fills up too.
            </Text>
          </View>
        }
      />
    );
  }

  return (
    <FlatList
      data={rows}
      keyExtractor={(row) => (row.kind === 'ad' ? row.key : row.item.id)}
      renderItem={({ item: row }) => (row.kind === 'ad' ? <FeedAd /> : <PostCard item={row.item} meId={user.id} />)}
      contentContainerStyle={{ paddingBottom: 24 }}
      refreshControl={<RefreshControl refreshing={isRefetching} onRefresh={refetch} />}
    />
  );
}

const styles = StyleSheet.create({
  container: { padding: 16 },
  center: { flex: 1, marginTop: 40 },
  emptyWrap: { flexGrow: 1, justifyContent: 'center' },
  emptyTitle: { fontSize: 20, fontWeight: '700', marginBottom: 8 },
  muted: { color: '#6B7280', lineHeight: 20 },
});
