-- CardLink — initial schema
-- Applied via `supabase db push` (or the Supabase SQL editor for the first run).
-- Do not edit this file after it has been applied anywhere — add a new migration instead.

-- ============================================================================
-- Catalog tables (card data cached from TCG provider APIs — see
-- src/services/tcg-providers/. Populated by a sync job, not by end users.)
-- ============================================================================

create table tcg_games (
  id text primary key,              -- 'pokemon' | 'mtg' | 'yugioh' ...
  name text not null,
  created_at timestamptz not null default now()
);

create table card_sets (
  id text primary key,              -- namespaced, e.g. 'pokemon:base1'
  game_id text not null references tcg_games(id),
  name text not null,
  series text,
  release_date date,
  total_cards int not null default 0,
  image_url text,
  created_at timestamptz not null default now()
);
create index card_sets_game_id_idx on card_sets(game_id);

create table cards (
  id text primary key,              -- namespaced, e.g. 'pokemon:base1-1'
  game_id text not null references tcg_games(id),
  set_id text not null references card_sets(id),
  name text not null,
  number text not null,
  rarity text,
  image_url_small text,
  image_url_large text,
  raw jsonb,                        -- full provider payload, for fields not yet modeled
  created_at timestamptz not null default now()
);
create index cards_set_id_idx on cards(set_id);
create index cards_name_idx on cards using gin (to_tsvector('simple', name));

-- ============================================================================
-- User & social tables
-- ============================================================================

create table profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  display_name text,
  avatar_url text,
  bio text,
  favorite_game_id text references tcg_games(id),
  created_at timestamptz not null default now()
);

-- Auto-create a profile row (with a placeholder username) when a new auth user
-- signs up. Onboarding flow (Phase 2) should prompt the user to set a real,
-- unique username immediately after.
create function handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username)
  values (new.id, 'user_' || substr(new.id::text, 1, 8));
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure handle_new_user();

create table follows (
  follower_id uuid not null references profiles(id) on delete cascade,
  followee_id uuid not null references profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, followee_id),
  constraint no_self_follow check (follower_id <> followee_id)
);

-- ============================================================================
-- Collection & wishlist
-- ============================================================================

create table user_cards (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references profiles(id) on delete cascade,
  card_id text not null references cards(id),
  quantity int not null default 1 check (quantity > 0),
  condition text check (condition in ('mint','near_mint','excellent','good','played','poor')),
  is_for_trade boolean not null default false,
  image_url text,                   -- user's own scanned photo, if any
  acquired_at timestamptz not null default now()
);
create index user_cards_owner_id_idx on user_cards(owner_id);
create index user_cards_card_id_idx on user_cards(card_id);

create table wishlists (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references profiles(id) on delete cascade,
  card_id text not null references cards(id),
  created_at timestamptz not null default now(),
  unique (user_id, card_id)
);
create index wishlists_card_id_idx on wishlists(card_id);

-- ============================================================================
-- Trading
-- ============================================================================

create table trades (
  id uuid primary key default gen_random_uuid(),
  initiator_id uuid not null references profiles(id),
  counterparty_id uuid not null references profiles(id),
  status text not null default 'proposed'
    check (status in ('proposed','countered','accepted','completed','declined','cancelled')),
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint no_self_trade check (initiator_id <> counterparty_id)
);
create index trades_initiator_id_idx on trades(initiator_id);
create index trades_counterparty_id_idx on trades(counterparty_id);

create table trade_items (
  id uuid primary key default gen_random_uuid(),
  trade_id uuid not null references trades(id) on delete cascade,
  user_card_id uuid not null references user_cards(id),
  from_user_id uuid not null references profiles(id)
);
create index trade_items_trade_id_idx on trade_items(trade_id);

-- NOTE: completing a trade (status -> 'completed') must transactionally
-- reassign owner_id on the involved user_cards rows. Implement as a
-- `supabase/functions/complete-trade` Edge Function or a Postgres function
-- called via RPC — do not do this as two separate client-side writes.

-- ============================================================================
-- Chat
-- ============================================================================

create table chat_threads (
  id uuid primary key default gen_random_uuid(),
  participant_one uuid not null references profiles(id),
  participant_two uuid not null references profiles(id),
  trade_id uuid references trades(id),
  card_id text references cards(id),
  created_at timestamptz not null default now(),
  constraint no_self_thread check (participant_one <> participant_two),
  constraint ordered_participants check (participant_one < participant_two),
  unique (participant_one, participant_two, trade_id, card_id)
);

create table chat_messages (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references chat_threads(id) on delete cascade,
  sender_id uuid not null references profiles(id),
  body text not null,
  image_url text,
  created_at timestamptz not null default now()
);
create index chat_messages_thread_id_idx on chat_messages(thread_id, created_at);

-- ============================================================================
-- Notifications
-- ============================================================================

create table notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references profiles(id) on delete cascade,
  type text not null check (type in ('wishlist_match','trade_update','chat_message','new_follower')),
  payload jsonb not null default '{}',
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index notifications_user_id_idx on notifications(user_id, created_at desc);

-- ============================================================================
-- Row Level Security
-- ============================================================================

alter table tcg_games enable row level security;
alter table card_sets enable row level security;
alter table cards enable row level security;
alter table profiles enable row level security;
alter table follows enable row level security;
alter table user_cards enable row level security;
alter table wishlists enable row level security;
alter table trades enable row level security;
alter table trade_items enable row level security;
alter table chat_threads enable row level security;
alter table chat_messages enable row level security;
alter table notifications enable row level security;

-- Catalog data: readable by anyone (including anon), writable only via
-- service role (sync jobs), so no insert/update/delete policies are defined.
create policy "catalog readable by all" on tcg_games for select using (true);
create policy "catalog readable by all" on card_sets for select using (true);
create policy "catalog readable by all" on cards for select using (true);

-- Profiles: public read (collections/profile pages are browsable), owner-only write.
create policy "profiles readable by all" on profiles for select using (true);
create policy "profiles updatable by owner" on profiles for update using (auth.uid() = id);

-- Follows: public read (needed to show follower/following lists), owner-only write.
create policy "follows readable by all" on follows for select using (true);
create policy "follow as self" on follows for insert with check (auth.uid() = follower_id);
create policy "unfollow as self" on follows for delete using (auth.uid() = follower_id);

-- User cards: public read (collections are browsable, per README §1), owner-only write.
create policy "user_cards readable by all" on user_cards for select using (true);
create policy "user_cards writable by owner" on user_cards
  for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);

-- Wishlists: owner-only read/write for now. Matching (Phase 4) runs via a
-- service-role Edge Function, which bypasses RLS, so it can still see all rows.
create policy "wishlists readable by owner" on wishlists for select using (auth.uid() = user_id);
create policy "wishlists writable by owner" on wishlists
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Trades: visible/editable only by the two participants.
create policy "trades readable by participants" on trades
  for select using (auth.uid() in (initiator_id, counterparty_id));
create policy "trades insertable by initiator" on trades
  for insert with check (auth.uid() = initiator_id);
create policy "trades updatable by participants" on trades
  for update using (auth.uid() in (initiator_id, counterparty_id));

create policy "trade_items readable by trade participants" on trade_items
  for select using (
    exists (
      select 1 from trades t
      where t.id = trade_items.trade_id
        and auth.uid() in (t.initiator_id, t.counterparty_id)
    )
  );
create policy "trade_items insertable by trade participants" on trade_items
  for insert with check (
    exists (
      select 1 from trades t
      where t.id = trade_items.trade_id
        and auth.uid() in (t.initiator_id, t.counterparty_id)
    )
  );

-- Chat: visible/editable only by the two participants of the thread.
create policy "chat_threads readable by participants" on chat_threads
  for select using (auth.uid() in (participant_one, participant_two));
create policy "chat_threads insertable by participants" on chat_threads
  for insert with check (auth.uid() in (participant_one, participant_two));

create policy "chat_messages readable by thread participants" on chat_messages
  for select using (
    exists (
      select 1 from chat_threads th
      where th.id = chat_messages.thread_id
        and auth.uid() in (th.participant_one, th.participant_two)
    )
  );
create policy "chat_messages insertable by thread participants" on chat_messages
  for insert with check (
    sender_id = auth.uid()
    and exists (
      select 1 from chat_threads th
      where th.id = chat_messages.thread_id
        and auth.uid() in (th.participant_one, th.participant_two)
    )
  );

-- Notifications: owner-only read/write. Rows are inserted by service-role
-- jobs (wishlist matcher, trade/chat triggers), which bypass RLS.
create policy "notifications readable by owner" on notifications for select using (auth.uid() = user_id);
create policy "notifications updatable by owner" on notifications for update using (auth.uid() = user_id);
